### ISSUE TITLE
Instalacja

### ISSUE THREAD

**Issue by sieekuu** [Encryptize/mikrus-recykling-notifier#1]
Dodajcie do readme instrukcje instalacji i konfiguracji takiego bota na swoim mikrusie. Bo to można do innych rzeczy jeszcze wykorzystać ale potrzebna instrukcja od autora jak to zainstalować.

**Comment by encryptize** [comment]
Instrukcja została dodana. https://github.com/Encryptize/mikrus-recykling-notifier/commit/56de502d75a14d9b80953b8c512e812768ffa9cf
