### ISSUE TITLE
Oznaczenie grupy użytkowników, jeżeli istnieje serwer do recyklingu

### ISSUE THREAD

**Issue by redex2** [Encryptize/mikrus-recykling-notifier#2]
Cześć!
Proponuje dodać możliwość oznaczenia grupy użytkowników, jeżeli znajduje się jakiś serwer do recyklingu. Pozwoli to na redukcje ilości powiadomień, a jednocześnie zainteresowani nie przegapią dodanych serwerów.

**Comment by encryptize** [comment]
Dodane :) https://github.com/Encryptize/mikrus-recykling-notifier/commit/2feb8d5a29bc0e76c47b74150ba89b4f38b3dfe0
